name: "Solar System Workflow"
on:
    workflow_dispatch:
    push:
        branches:
            - main
jobs:
    unit-testing:
        name: "Unit Testing"
        runs-on: ubuntu-latest
        steps:
            - name: "Checkout the Repo"
              uses: actions/checkout@v4
            - name: "Setup Node JS"
              uses: actions/setup-node@v4
              with:
                node-version: 20
            - name: Install Dependencies
              uses: npm install
            - name: Unit Testing
              uses: npm test
            - name: Archive Test Results
              uses: actions/upload-artifact@v4
              with:
                name: app-test-results
                path: test-results.xml





